USE [master]
GO

/****** Object:  Database [PeregrineDB]    Script Date: 12/12/2011 17:49:07 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'PeregrineDB')
DROP DATABASE [PeregrineDB]
GO

USE [master]
GO

/****** Object:  Database [PeregrineDB]    Script Date: 12/12/2011 17:49:07 ******/
CREATE DATABASE [PeregrineDB] ON  PRIMARY 
( NAME = N'PeregrineDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\PeregrineDB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PeregrineDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\PeregrineDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PeregrineDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PeregrineDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PeregrineDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PeregrineDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PeregrineDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PeregrineDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PeregrineDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PeregrineDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PeregrineDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [PeregrineDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PeregrineDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PeregrineDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PeregrineDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PeregrineDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PeregrineDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PeregrineDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PeregrineDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PeregrineDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PeregrineDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PeregrineDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PeregrineDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PeregrineDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PeregrineDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PeregrineDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PeregrineDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PeregrineDB] SET  READ_WRITE 
GO

ALTER DATABASE [PeregrineDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PeregrineDB] SET  MULTI_USER 
GO

ALTER DATABASE [PeregrineDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PeregrineDB] SET DB_CHAINING OFF 
GO

